### ISSUE TITLE
Sign

### ISSUE THREAD

**Issue by artrag** [nanochess/IntyBASIC#6]
Something wrong with the jumps generated by the sign() implementation. Look at DZ-Jay explanations here 

http://atariage.com/forums/topic/274395-2018-contest-chat/page-4

**Comment by intvnut** [comment]
A more general question I've always had:  Why does IntyBASIC even do $+123 types of jumps, instead of emitting labels?  I realize it tries to be one-pass; however it should still be possible to branch to a label and defer emitting the label.

It also costs nothing to give the same location multiple labels.
