### ISSUE TITLE
Fixed point Data

### ISSUE THREAD

**Issue by artrag** [nanochess/IntyBASIC#8]
Using the fixed point math I've spotted this:

data	-0.7071,0.7071
                                	SRCFILE "testbasic.bas",48
				DECLE -46336
asm\testbasic.asm:1864: ERROR - expression exceeds available field width
asm\testbasic.asm:1864: ERROR - expression exceeds available field width

Negative fixed point constants are processed by intybasic but not by the assembler....

**Comment by intvnut** [comment]
AS1600 warns for constants outside the range [-32768, 65535].

**Comment by intvnut** [comment]
I don't think -46336 is a meaningful number here.  Masking with $FFFF (even if you could) is the wrong thing to do.



AS1600 allows the range -32768 to 65536, which encompases the entire signed and unsigned 16-bit ranges.  -46336 is outside both of those ranges.



As a fixed point number in Q8 notation, 0.707 is $00B5, and in the rotated Q8, would be $B500.   -0.707 would be $FF4B, and in rotated Q8, $4BFF.



-46336 is $FFFF4B00, which is the wrong value, since the negation is being applied to the rotated value.



Negation should be applied before rotation, resulting oin $4BFF.  (Or if it's 1s complement, $4AFF.  I forget, is the rotated Q8 in 1s complement?)
